### ISSUE TITLE
 parse_kaken_master/kaken_zenkadai_download.ipynb　　の最後のセルの後ろから2行目のコードについて

### ISSUE THREAD

**Issue by okutsu-saeko** [hiraikatsuyuki/parse_kaken_master#1]
ここからだとただのコメントになっちゃいますね？

with open(filename, mode='w') as f:
を
with open(filename, mode='w', encoding='utf-8') as f:
へ

とか書いてみても何か違うような気がするので他のところからもいじってみていいですか？

**Comment by hiraikatsuyuki** [comment]
ありがとうございます。
返事するのを忘れてました。今後はc4raのリポジトリで作っていきましょうー
